sudo: required
language: node_js
node_js:
  - 10
cache: yarn

install:
  - yarn install


script: |-
  set -e

  # 
  # Test
  # 
  yarn test

  # 
  # install awscli v2 for ecr upload
  # 
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  unzip /tmp/awscliv2.zip -d /tmp
  sudo /tmp/aws/install
  
  # 
  # Build docker image
  # 
  export IMAGE="${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_NAME}:v${TRAVIS_BUILD_NUMBER}-build"
  export IMAGE_LATEST="${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_NAME}:latest"

  docker build -t "$IMAGE" -t "$IMAGE_LATEST" \
    --build-arg "APP_ENV=production" \
    .

deploy:
  provider: script
  skip_cleanup: true
  script: |-
    export AWS_ACCESS_KEY_ID=$AWS_ECR_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$AWS_ECR_SECRET_ACCESS_KEY
    aws ecr get-login-password --region ${AWS_REGION} | docker login -u AWS --password-stdin ${AWS_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
    docker push "$IMAGE"
    docker push "$IMAGE_LATEST"